-- 归档字段
ALTER TABLE t_activity ADD is_archived TINYINT ( 1 ) DEFAULT 0 COMMENT '是否归档';
-- 课程id、班级id
ALTER TABLE t_activity ADD is_open_clazz_interaction TINYINT (1) DEFAULT  0 COMMENT '是否开启班级互动';
ALTER TABLE t_activity ADD course_id int(11) COMMENT '课程id';
ALTER TABLE t_activity ADD clazz_id int(11) COMMENT '班级id';
-- 班级互动组件
INSERT INTO `t_component` (`id`, `pid`, `name`, `code`, `is_required`, `introduction`, `is_system`, `is_multi`, `type`, `data_origin`, `origin_identify`, `field_flag`, `template_id`, `create_time`, `create_uid`, `update_time`, `update_uid`) VALUES (48, 0, '班级互动', 'clazz_interaction', 0, '', 1, 0, NULL, NULL, NULL, NULL, NULL, '2021-12-02 15:14:20', 172649568, '2021-12-02 15:14:20', 172649568);
-- 更新teacher模板字段排序，每个排序值增大五倍，以便后插入字段能够排序在其中间
UPDATE t_template_component set `sequence` = `sequence` * 5 where template_id = 4 and `sequence` != -1;
-- teacher 系统模板增加班级互动组件模板组件关联
INSERT INTO `t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (228, 0, 4, 48, '班级互动', '', 0, 46, 0, NULL, NULL, NULL, NULL);
-- 2021-12-07
INSERT INTO `t_system_notice_template` (`id`, `notice_type`, `receiver_description`, `title`, `code_title`, `content`, `code_content`, `send_time_description`, `is_support_time_config`, `delay_hour`, `delay_minute`, `is_enable`, `sequence`) VALUES (5, 'sign_up_about_end', '已收藏', '你收藏的<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动名称\" code=\"activity_name\" style=\"width: 55px;\">即将结束报名！', '你收藏的{activity_name}即将结束报名！', '活动名称：<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动名称\" code=\"activity_name\" style=\"width: 55px;\"><div>报名时间：<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"报名时间\" code=\"sign_up_time\" style=\"width: 55px;\"></div><div>活动时间：<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动时间\" code=\"activity_time\" style=\"width: 55px;\"></div>', '活动名称：{activity_name}\n报名时间：{sign_up_time}\n活动时间：{activity_time}\n', '报名结束前', 1, 24, 0, 1, 5);
INSERT INTO `t_system_notice_template` (`id`, `notice_type`, `receiver_description`, `title`, `code_title`, `content`, `code_content`, `send_time_description`, `is_support_time_config`, `delay_hour`, `delay_minute`, `is_enable`, `sequence`) VALUES (6, 'auto_add_to_blacklist', '黑名单用户', '您已被移入<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动主办方\" code=\"activity_organisers\" style=\"width: 65px;\">黑名单！', '您已被移入{activity_organisers}黑名单！', '您好，由于您未签到（签退）次数达到上限，已自动进入黑名单，将在【自动解除时间】自动解除，【需管理员手动解除黑名单】在此期间内将无法参加任何该单位活动，若有疑问请联系单位管理员。 点击此处联系管理员>><div>未签到/签退活动名称：<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动名称\" code=\"activity_name\" style=\"width: 55px;\"></div><div>活动时间：<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动名称\" code=\"activity_name\" style=\"width: 55px;\"></div>', '您好，由于您未签到（签退）次数达到上限，已自动进入黑名单，将在【自动解除时间】自动解除，【需管理员手动解除黑名单】在此期间内将无法参加任何该单位活动，若有疑问请联系单位管理员。 点击此处联系管理员>>\n\n未签到/签退活动名称：{activity_name}\n活动时间：{activity_time}\n', '未签到/签退', 0, 0, 0, 1, 6);
INSERT INTO `t_system_notice_template` (`id`, `notice_type`, `receiver_description`, `title`, `code_title`, `content`, `code_content`, `send_time_description`, `is_support_time_config`, `delay_hour`, `delay_minute`, `is_enable`, `sequence`) VALUES (7, 'manual_add_to_blacklist', '黑名单用户', '您已被<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动主办方\" code=\"activity_organisers\" style=\"width: 65px;\">移入黑名单！', '您已被{activity_organisers}移入黑名单！', '您好，您已被<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动主办方\" code=\"activity_organisers\" style=\"width: 65px;\">拉入黑名单，若有疑问请联系单位管理员。 点击此处联系管理员>>', '您好，您已被{activity_organisers}拉入黑名单，若有疑问请联系单位管理员。 点击此处联系管理员>>\n', '未签到/签退', 0, 0, 0, 1, 7);
INSERT INTO `t_system_notice_template` (`id`, `notice_type`, `receiver_description`, `title`, `code_title`, `content`, `code_content`, `send_time_description`, `is_support_time_config`, `delay_hour`, `delay_minute`, `is_enable`, `sequence`) VALUES (8, 'remove_from_blacklist', '黑名单用户', '您已被移出<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动主办方\" code=\"activity_organisers\" style=\"width: 65px;\">黑名单！', '您已被移出{activity_organisers}黑名单！', '您好，您已被<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"活动主办方\" code=\"activity_organisers\" style=\"width: 65px;\">移出黑名单，可参加该单位的活动。<div>移入黑名单时间：<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"黑名单进入时间\" code=\"blacklist_add_time\" style=\"width: 95px;\"></div><div>移出黑名单时间：<input type=\"text\" class=\"tag\" readonly=\"readonly\" value=\"黑名单移出时间\" code=\"blacklist_remove_time\" style=\"width: 95px;\"></div>', '您好，您已被{activity_organisers}移出黑名单，可参加该单位的活动。\n\n移入黑名单时间：{blacklist_add_time}\n移出黑名单时间：{blacklist_remove_time}\n', '未签到/签退', 0, 0, 0, 1, 8);

