spring:
  application:
    name: activity-engine
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
  ## 静态资源处理方式
  resources:
    chain:
      cache: true
      strategy:
        content:
          enabled: true
          paths: /**
    static-locations: classpath:/META-INF/resources/,classpath:/static/,classpath:/public/,classpath:/upload/,file:./upload/
  ## 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        config:
          enabled: true
      connection-init-sqls: set names utf8mb4;
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      async-init: true
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: druid_passwd
  ## redis相关
  redis:
    timeout: 10000
  servlet:
    multipart:
      ## 上传一个文件最大值
      max-file-size: 100MB
      ## 上传多个文件最大值
      max-request-size: 100MB
  cache:
    type: redis
mybatis:
  ## mybatis mapper文件路径
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  global-config:
    db-config:
      ## 逻辑已删除值
      logic-delete-value: 0
      ## 逻辑未删除值
      logic-not-delete-value: 1
server:
  servlet:
    session:
      ##解决静态url带jsessionid问题
      tracking-modes: cookie
    encoding:
      force: true
  tomcat:
    ## 不限制post的大小
    max-http-form-post-size: -1