spring:
  application:
    name: activity-engine
  profiles:
    active: local
  ## 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-init-sqls: set names utf8mb4;
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      async-init: true
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1,216.24.178.244
        reset-enable: false
        loginUsername: 18781935192
        loginPassword: NIio6VsBHLZ6AguL
      filters: stat,wall,log4j2
      ## 状态监控
      filter:
        enabled: true
        db-type: mysql
        log-slow-sql: true
        slow-sql-millis: 2000
      ## 监控过滤器
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
      aop-patterns: com.chaoxing.activity.service.manager.*
  ## redis相关
  redis:
    redisson:
      config:
        single_server_config:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 64
          connectionPoolSize: 128
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
mybatis:
  ## mybatis mapper文件路径
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  global-config:
    db-config:
      ## 逻辑已删除值
      logic-delete-value: 0
      ## 逻辑未删除值
      logic-not-delete-value: 1
certificate:
  qr_code:
    path: /certificate/qr_code