-- 增加培训training、课题subject、工作室studio模板
INSERT INTO `activity_engine`.`t_template` (`id`, `name`, `market_id`, `origin_template_id`, `is_system`, `activity_flag`, `fid`, `cover_url`, `sequence`, `create_time`, `create_uid`, `update_time`, `update_uid`) VALUES (13, '培训', NULL, NULL, 1, 'training', NULL, NULL, 13, '2021-12-09 14:29:31', 172649568, '2021-12-09 14:15:50', 172649568);
INSERT INTO `activity_engine`.`t_template` (`id`, `name`, `market_id`, `origin_template_id`, `is_system`, `activity_flag`, `fid`, `cover_url`, `sequence`, `create_time`, `create_uid`, `update_time`, `update_uid`) VALUES (14, '课题', NULL, NULL, 1, 'subject', NULL, NULL, 14, '2021-12-09 14:29:31', 172649568, '2021-12-09 14:15:50', 172649568);
INSERT INTO `activity_engine`.`t_template` (`id`, `name`, `market_id`, `origin_template_id`, `is_system`, `activity_flag`, `fid`, `cover_url`, `sequence`, `create_time`, `create_uid`, `update_time`, `update_uid`) VALUES (15, '工作室', NULL, NULL, 1, 'studio', NULL, NULL, 15, '2021-12-09 14:29:31', 172649568, '2021-12-09 14:15:50', 172649568);


-- 增加培训training模板组件关联
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (228, 0, 13, 1, '名称', NULL, 1, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (229, 0, 13, 2, '活动时间', NULL, 1, 2, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (230, 0, 13, 3, '封面', NULL, 1, 3, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (231, 0, 13, 4, '主办方', NULL, 0, 4, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (232, 0, 13, 5, '类型', NULL, 0, 5, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (233, 0, 13, 6, '分类', NULL, 0, 6, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (234, 0, 13, 11, '发布范围', '按照区域架构选择活动范围', 1, 9, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (235, 0, 13, 13, '报名', NULL, 0, 10, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (236, 0, 13, 39, '签到', NULL, 0, 11, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (237, 0, 13, 15, '签退', NULL, 0, 12, 1, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (238, 0, 13, 17, '标签', NULL, 0, 13, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (239, 0, 13, 19, '定时发布', '开启后，可以按照设置的时间自动发布活动', 0, 14, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (240, 0, 13, 20, '简介', NULL, 0, 15, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (241, 235, 13, 30, '报名时间', NULL, 1, 16, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (242, 235, 13, 33, '人数限制', NULL, 0, 17, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (243, 235, 13, 34, '报名填报信息', '开启后，报名者需填写信息', 0, 18, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (244, 235, 13, 35, '报名需要审核', '报名需活动管理员审核', 0, 19, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (245, 235, 13, 36, '报名名单公开', '开启后，所有人都能看到报名人员名单', 0, 20, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (246, 235, 13, 37, '取消报名设置', '开启后，指定时间后参与者不能取消报名', 0, 21, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (247, 0, 13, 40, '基本信息', '', 0, -1, 0, NULL, NULL, NULL, NULL);

-- 增加课题subject模板组件关联
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (248, 0, 14, 1, '名称', NULL, 1, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (249, 0, 14, 2, '活动时间', NULL, 1, 2, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (250, 0, 14, 3, '封面', NULL, 1, 3, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (251, 0, 14, 4, '主办方', NULL, 0, 4, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (252, 0, 14, 5, '类型', NULL, 0, 5, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (253, 0, 14, 6, '分类', NULL, 0, 6, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (254, 0, 14, 11, '发布范围', '按照区域架构选择活动范围', 1, 9, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (255, 0, 14, 13, '报名', NULL, 0, 10, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (256, 0, 14, 39, '签到', NULL, 0, 11, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (257, 0, 14, 15, '签退', NULL, 0, 12, 1, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (258, 0, 14, 17, '标签', NULL, 0, 13, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (259, 0, 14, 19, '定时发布', '开启后，可以按照设置的时间自动发布活动', 0, 14, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (260, 0, 14, 20, '简介', NULL, 0, 15, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (261, 255, 14, 30, '报名时间', NULL, 1, 16, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (262, 255, 14, 33, '人数限制', NULL, 0, 17, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (263, 255, 14, 34, '报名填报信息', '开启后，报名者需填写信息', 0, 18, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (264, 255, 14, 35, '报名需要审核', '报名需活动管理员审核', 0, 19, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (265, 255, 14, 36, '报名名单公开', '开启后，所有人都能看到报名人员名单', 0, 20, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (266, 258, 14, 37, '取消报名设置', '开启后，指定时间后参与者不能取消报名', 0, 21, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (267, 0, 14, 40, '基本信息', '', 0, -1, 0, NULL, NULL, NULL, NULL);

-- 增加工作室studio模板组件关联
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (268, 0, 15, 1, '名称', NULL, 1, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (269, 0, 15, 2, '活动时间', NULL, 1, 2, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (270, 0, 15, 3, '封面', NULL, 1, 3, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (271, 0, 15, 4, '主办方', NULL, 0, 4, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (272, 0, 15, 5, '类型', NULL, 0, 5, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (273, 0, 15, 6, '分类', NULL, 0, 6, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (274, 0, 15, 11, '发布范围', '按照区域架构选择活动范围', 1, 9, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (275, 0, 15, 13, '报名', NULL, 0, 10, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (276, 0, 15, 39, '签到', NULL, 0, 11, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (277, 0, 15, 15, '签退', NULL, 0, 12, 1, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (278, 0, 15, 17, '标签', NULL, 0, 13, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (279, 0, 15, 19, '定时发布', '开启后，可以按照设置的时间自动发布活动', 0, 14, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (280, 0, 15, 20, '简介', NULL, 0, 15, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (281, 236, 15, 30, '报名时间', NULL, 1, 16, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (282, 236, 15, 33, '人数限制', NULL, 0, 17, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (283, 236, 15, 34, '报名填报信息', '开启后，报名者需填写信息', 0, 18, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (284, 236, 15, 35, '报名需要审核', '报名需活动管理员审核', 0, 19, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (285, 236, 15, 36, '报名名单公开', '开启后，所有人都能看到报名人员名单', 0, 20, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (286, 236, 15, 37, '取消报名设置', '开启后，指定时间后参与者不能取消报名', 0, 21, 0, NULL, NULL, NULL, NULL);
INSERT INTO `activity_engine`.`t_template_component` (`id`, `pid`, `template_id`, `component_id`, `name`, `introduction`, `is_required`, `sequence`, `is_deleted`, `type`, `data_origin`, `origin_identify`, `field_flag`) VALUES (287, 0, 15, 40, '基本信息', '', 0, -1, 0, NULL, NULL, NULL, NULL);



