spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: icu
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1/activity_engine?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: admin
proxy:
  enable: true