spring:
  redis:
    host: 192.168.1.10
    port: 6379
    database: 11
    password: be_api

  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3307/activity_engine?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: master
      password: master