spring:
  redis:
    host: 10.0.23.238
    port: 6379
    database: 11
    password: be
  datasource:
    druid:
      url: jdbc:mysql://10.0.17.34/sign_activity?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: master
      password: master
server:
  port: 8104