spring:
  application:
    name: activity-engine
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
  ##\u9759\u6001\u8D44\u6E90\u5904\u7406\u65B9\u5F0F
  resources:
    chain:
      cache: true
      strategy:
        content:
          enabled: true
          paths: /**
    static-locations: classpath:/META-INF/resources/,classpath:/static/,classpath:/public/,classpath:/upload/,file:./upload/
  ##\u6570\u636E\u5E93
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #      connect-properties: config.decrypt=true
      filter:
        config:
          enabled: true
      connection-init-sqls: set names utf8mb4;
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      async-init: true
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: druid_passwd
  ##redis\u76F8\u5173
  redis:
    jedis:
      pool:
        max-active: 500
        ##\u8FDE\u63A5\u6C60\u7684\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF08-1\u8868\u793A\u65E0\u9650\u5236\uFF09
        max-wait: -1
        ##\u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 100
        ##\u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 50
      ##\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
      time-out: 10000
  servlet:
    multipart:
      #$\u4E0A\u4F20\u4E00\u4E2A\u6587\u4EF6\u6700\u5927\u503C
      max-file-size: 100MB
      ##\u4E0A\u4F20\u591A\u4E2A\u6587\u4EF6\u6700\u5927\u503C
      max-request-size: 100MB
  cache:
    type: redis
mybatis:
  ## mybatis mapper\u6587\u4EF6\u8DEF\u5F84
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    session:
      ##\u89E3\u51B3\u9759\u6001url\u5E26jsessionid\u95EE\u9898
      tracking-modes: cookie
    encoding:
      force: true
  tomcat:
    ## \u4E0D\u9650\u5236post\u7684\u5927\u5C0F
    max-http-form-post-size: -1